name: 3D Contribution Map

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  contrib:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ShabalalaWATP

      - name: Push 3D contrib
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add profile-3d-contrib/
          git commit -m "update 3D contribution map" || true
          git push
